export const assets = ['Bitcoin', 'Corn', 'ZCash', 'Reddit', 'Dash', 'Ripple', 'Bitcoin'];

export const langCodes = {
	en: 'en-US',
	es: 'es-419',
	pt: 'pt-BR'
};

export const countries = [
	'Brazil',
	'Argentina',
	'Colombia',
	'Mexico',
	'Venezuela',
	'Paraguay',
	'El Salvador',
	'Chile',
	'Ecuador',
	'Peru',
	'Bolivia',
	'Jamaica',
	'Costa Rica',
	'Guatemala',
	'Nicaragua',
	'Uruguay',
	'Honduras',
	'Panama'
];

export const names = [
	'Alexandro G.',
	'Enrico L.',
	'Sasha M.',
	'Daniel P.',
	'Eduardo S.',
	'Felipe R.',
	'Gabriel L.',
	'Hugo N.',
	'Ivan D.',
	'Jorge F.',
	'Lucas H.',
	'Marcelo J.',
	'Nathan W.',
	'Otavio A.',
	'Paulo K.',
	'Ricardo V.',
	'Alejandro G.',
	'Carlos M.',
	'Diego R.',
	'Javier S.',
	'José L.',
	'Manuel D.',
	'Mateo B.',
	'Miguel C.',
	'Nicolás V.',
	'Pablo F.',
	'Ricardo E.',
	'Santiago T.',
	'Tomás N.',
	'Eduardo H.',
	'Ana C.',
	'Camila R.',
	'Carolina V.',
	'Daniela G.',
	'Gabriela S.',
	'Isabel C.',
	'Laura F.',
	'María L.',
	'Sofía B.',
	'Valentina D.'
];
